import js from "@eslint/js";

export default [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: "module",
      globals: {
        window: "readonly",
        document: "readonly",
        console: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        fetch: "readonly",
        navigator: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        clearTimeout: "readonly",
        Intl: "readonly",
        HTMLElement: "readonly",
        HTMLImageElement: "readonly",
        Element: "readonly",
        MutationObserver: "readonly",
        IntersectionObserver: "readonly",
        FormData: "readonly",
        TextEncoder: "readonly",
        Chart: "readonly",
        crypto: "readonly",
        matchMedia: "readonly",
        AudioContext: "readonly",
        OscillatorNode: "readonly",
        GainNode: "readonly",
        BiquadFilterNode: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        alert: "readonly",
        confirm: "readonly",
        performance: "readonly",
        Blob: "readonly",
        google: "readonly",
      },
    },
    rules: {
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      "no-console": ["warn", { allow: ["warn", "error"] }],
      "prefer-const": "error",
      "no-var": "error",
      eqeqeq: ["error", "always"],
      curly: ["error", "multi-line"],
      "no-throw-literal": "error",
      "no-extra-boolean-cast": "error",
      "no-useless-constructor": "error",
      "no-useless-rename": "error",
      "no-useless-return": "error",
      "object-shorthand": ["error", "always"],
      "prefer-template": "error",
      "no-lonely-if": "error",
      "no-else-return": "error",
      "no-unneeded-ternary": "error",
      "prefer-arrow-callback": "error",
      "no-param-reassign": "warn",
    },
  },
  {
    ignores: ["node_modules/", ".netlify/", "tests/"],
  },
];
